### ISSUE TITLE
Edge Label Width Incorrect 

### ISSUE THREAD

**Issue by wdfinch** [wbkd/react-flow#419] opened 2020-08-10 18:34 UTC
I'm noticing that the width on the background rect element for edge labels is too small for the provided text. This means the background color is not fully covering the text.

I think the issue is the edgeRef is calculating the width before the element has finished rendering in some cases. I'm able to solve the issue by adding a small delay to checking textBbox.width.

**Comment by moklick** [comment] 2020-08-10 20:11
Sorry I can't reproduce this. Can you create a codsandbox?

**Comment by wdfinch** [comment] 2020-08-10 20:52
https://codesandbox.io/s/cranky-worker-dymfw?file=/src/App.js

I believe the issue occurs when using a custom font for the edge label. The font needs to load and the size is calculated before the font is initialized. It is not updated when the ref width changes.

The sandbox will only show the incorrect width on the first load as the font will get cached by the browser. You can try dumping the cache to see the issue occurring again.

I am getting this every time I reload in my project but I think that just a caching detail with how I'm loading my assets.

**Comment by moklick** [comment] 2020-08-10 21:35
You are right. It is because of the font that is not loaded when we measure the dimensions of the label. I would not add a delay, because we never know when the font is loaded. Maybe you are able to handle this issue when you use a foreignObject as a label.  Either way, I would like to close this issue as it is an edge case in my view.

**Closed by moklick** 2020-08-10 21:35 UTC

**Comment by wdfinch** [comment] 2020-08-10 21:49
Sounds good. Yes, the delay was a temp fix. I wish there was an easy way to know when edgeRef.current.getBBox() had a new width, but I guess this isn't possible using a hook.

**Comment by moklick** [comment] 2020-08-10 22:13
We are using `ResizeObserver` for the nodes but I think it's a bit too much for the edge texts.

**Comment by kbaird5** [comment] 2020-10-07 04:52
Also seeing a similar issue when dynamically changing the edge label text. The text is updated, but the rectangle stays the size of the original label.
