### ISSUE TITLE
Custom Node onMouseDown event not work

### ISSUE THREAD

**Issue by l1shen** [wbkd/react-flow#2401] opened 2022-09-05 07:25 UTC
### Describe the Bug

```ts
export function MouseDownNode({ data }) {
  const onMouseDown = (e) => {
    console.log('onMouseDown', e);
  };

  return (
    <div onMouseDown={onMouseDown}>
      <div>MouseDownNode</div>
    </div>
  );
}
```
click MouseDownNode no onMouseDown event

### Your Example Website or App

https://stackblitz.com/edit/react-ts-sui62s?file=test-node.tsx

### Steps to Reproduce the Bug or Issue

click MouseDownNode

### Expected behavior

has onMouseDown event

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment] 2022-09-05 07:40
duplicate of #2341 

`onMouseDownCapture` should work.

**Closed by moklick** 2022-09-05 07:40 UTC

**Comment by maramzan** [comment] 2022-10-06 08:25
> duplicate of #2341
> 
> `onMouseDownCapture` should work.

@moklick 

What about onMouseUp...?
because onMouseUpCapture not Working

**Comment by kurtgrung** [comment] 2023-11-15 04:30
I need `onMouseUpCapture` too.

**Comment by bigmistqke** [comment] 2023-12-19 15:05
+1 for `onMouseCapture`. It is a blocker in a project of mine. It's pretty unfortunate there is no escape hatch to set normal event listeners.

**Comment by moklick** [comment] 2023-12-19 17:58
an escape hatch is to add class name "nodrag" to the element where you want to capture the mouse down event: https://codesandbox.io/p/sandbox/polished-morning-l67y43?file=%2Fsrc%2FCustomNode.tsx%3A24%2C22
