### ISSUE TITLE
After using react flow latest version storybook can't build 

### ISSUE THREAD

**Issue by avishwakarmaplex** [wbkd/react-flow#2724] opened 2023-01-02 20:22 UTC
### Describe the Bug

I'm currently been using react flow latest version:11.4.0 with yarn 1.22.10
and created a component integrated it with storybook storybook v6.3.3 and using node version:  v16.19.0, react version: 18.2.0

everytime i build, it ends up saying the ModuleParseError: Module parse failed: Unexpected token, i tried downgrading many version of react flow but still wasn't able to get it running

Can someone please help me on this 

### Steps to Reproduce the Bug or Issue

```
// FlowCanvas.tsx
import React, { useCallback } from "react";
import ReactFlow, { MiniMap, Controls, Background, useNodesState, useEdgesState, addEdge } from "reactflow";

import "reactflow/dist/style.css";

const initialNodes = [
  { id: "1", position: { x: 0, y: 0 }, data: { label: "1" } },
  { id: "2", position: { x: 0, y: 100 }, data: { label: "2" } }
];

const initialEdges = [{ id: "e1-2", source: "1", target: "2" }];

/**
 This is a Flow Canvas Component
 */
export const FlowCanvas: FunctionComponent = () => {
  const [nodes, , onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

  const onConnect = useCallback(params => setEdges(eds => addEdge(params, eds)), [setEdges]);

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      onConnect={onConnect}
    >
      <MiniMap />
      <Controls />
      <Background />
    </ReactFlow>
  );
};

FlowCanvas.displayName = "FlowCanvas";
```

Output Error: 
ERROR in ./node_modules/@reactflow/minimap/dist/esm/index.js 41:31
Module parse failed: Unexpected token (41:31)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const svg = useRef(null);
|     const { boundingRect, viewBB, nodes, rfId, nodeOrigin } = useStore(selector, shallow);
>     const elementWidth = style?.width ?? defaultWidth;
|     const elementHeight = style?.height ?? defaultHeight;
|     const nodeColorFunc = getAttrFunction(nodeColor);
 @ ./node_modules/reactflow/dist/esm/index.js 3:0-35 3:0-35
 @ ./packages/boom-react-components/src/components/Flow/FlowCanvas.tsx
 @ ./packages/boom-react-components/src/components/Flow/FlowCanvas.stories.tsx
 @ ./packages sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(tsx|js|mdx))$
 @ ./generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js

ERROR in ./node_modules/@reactflow/controls/dist/esm/index.js 43:17
Module parse failed: Unexpected token (43:17)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const onZoomInHandler = () => {
|         zoomIn();
>         onZoomIn?.();
|     };
|     const onZoomOutHandler = () => {
 @ ./node_modules/reactflow/dist/esm/index.js 4:0-36 4:0-36
 @ ./packages/boom-react-components/src/components/Flow/FlowCanvas.tsx
 @ ./packages/boom-react-components/src/components/Flow/FlowCanvas.stories.tsx
 @ ./packages sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(tsx|js|mdx))$
 @ ./generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js

ERROR in ./node_modules/@reactflow/core/dist/esm/index.js 43:19
Module parse failed: Unexpected token (43:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| function Attribution({ proOptions, position = 'bottom-right' }) {
>     if (proOptions?.hideAttribution) {
|         return null;
|     }
 @ ./node_modules/reactflow/dist/esm/index.js 1:0-32 1:0-32 2:0-55 2:0-55
 @ ./packages/boom-react-components/src/components/Flow/FlowCanvas.tsx
 @ ./packages/boom-react-components/src/components/Flow/FlowCanvas.stories.tsx
 @ ./packages sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(tsx|js|mdx))$
 @ ./generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js

ERROR in ./node_modules/@reactflow/node-toolbar/dist/esm/index.js 8:42
Module parse failed: Unexpected token (8:42)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { createPortal } from 'react-dom';
|
> const selector = (state) => state.domNode?.querySelector('.react-flow__renderer');
| function NodeToolbarPortal({ children }) {
|     const wrapperRef = useStore(selector);
 @ ./node_modules/reactflow/dist/esm/index.js 6:0-40 6:0-40
 @ ./packages/boom-react-components/src/components/Flow/FlowCanvas.tsx
 @ ./packages/boom-react-components/src/components/Flow/FlowCanvas.stories.tsx
 @ ./packages sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(tsx|js|mdx))$
 @ ./generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.28 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/templates/index.ejs] 2.07 KiB {HtmlWebpackPlugin_0} [built]
WARN Force closed manager build
ModuleParseError: Module parse failed: Unexpected token (41:31)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const svg = useRef(null);
|     const { boundingRect, viewBB, nodes, rfId, nodeOrigin } = useStore(selector, shallow);
>     const elementWidth = style?.width ?? defaultWidth;
|     const elementHeight = style?.height ?? defaultHeight;
|     const nodeColorFunc = getAttrFunction(nodeColor);
    at handleParseError (C:\Dev\Git\random\boom-react-components\node_modules\webpack\lib\NormalModule.js:469:19)
    at C:\Dev\Git\random\boom-react-components\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Dev\Git\random\boom-react-components\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Dev\Git\random\boom-react-components\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Dev\Git\random\boom-react-components\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Dev\Git\random\boom-react-components\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Dev\Git\random\boom-react-components\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Dev\Git\random\boom-react-components\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Dev\Git\random\boom-react-components\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
ModuleParseError: Module parse failed: Unexpected token (43:17)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const onZoomInHandler = () => {
|         zoomIn();
>         onZoomIn?.();
|     };
|     const onZoomOutHandler = () => {
    at handleParseError (C:\Dev\Git\random\boom-react-components\node_modules\webpack\lib\NormalModule.js:469:19)
    at C:\Dev\Git\random\boom-react-components\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Dev\Git\random\boom-react-components\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Dev\Git\random\boom-react-components\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Dev\Git\random\boom-react-components\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Dev\Git\random\boom-react-components\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Dev\Git\random\boom-react-components\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Dev\Git\random\boom-react-components\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Dev\Git\random\boom-react-components\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
ModuleParseError: Module parse failed: Unexpected token (43:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| function Attribution({ proOptions, position = 'bottom-right' }) {
>     if (proOptions?.hideAttribution) {
|         return null;
|     }
    at handleParseError (C:\Dev\Git\random\boom-react-components\node_modules\webpack\lib\NormalModule.js:469:19)
    at C:\Dev\Git\random\boom-react-components\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Dev\Git\random\boom-react-components\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Dev\Git\random\boom-react-components\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Dev\Git\random\boom-react-components\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Dev\Git\random\boom-react-components\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Dev\Git\random\boom-react-components\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Dev\Git\random\boom-react-components\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Dev\Git\random\boom-react-components\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
ModuleParseError: Module parse failed: Unexpected token (8:42)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { createPortal } from 'react-dom';
|
> const selector = (state) => state.domNode?.querySelector('.react-flow__renderer');
| function NodeToolbarPortal({ children }) {
|     const wrapperRef = useStore(selector);
    at handleParseError (C:\Dev\Git\random\boom-react-components\node_modules\webpack\lib\NormalModule.js:469:19)
    at C:\Dev\Git\random\boom-react-components\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Dev\Git\random\boom-react-components\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Dev\Git\random\boom-react-components\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Dev\Git\random\boom-react-components\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Dev\Git\random\boom-react-components\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Dev\Git\random\boom-react-components\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Dev\Git\random\boom-react-components\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Dev\Git\random\boom-react-components\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info => Loading presets
? Would you like to send crash reports to Storybook? » (Y/n)

### Expected behavior

Ideally the React flow components should be build and run 

### Platform

- OS: [Windows]
- Browser: [Chrome]
- React flow latest version:11.4.0
 yarn: 1.22.10
 Storybook: v6.3.3
 node version:  v16.19.0
 React: 18.2.0

**Comment by moklick** [comment] 2023-01-04 12:16
Thanks! We will check that.

duplicate of #2652

**Closed by moklick** 2023-01-04 12:16 UTC
