### ISSUE TITLE
With Webpack Build Error for React Flow V11

### ISSUE THREAD

**Issue by bahubaliSITH** [wbkd/react-flow#2843] opened 2023-02-14 11:28 UTC
### Describe the Bug

Failed to compile.

./node_modules/@reactflow/core/dist/esm/index.js 71:17
Module parse failed: Unexpected token (71:17)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     position = 'bottom-right'
|   } = _ref2;
>   if (proOptions?.hideAttribution) {
|     return null;
|   }

### Steps to Reproduce the Bug or Issue

1. Install React Flow
2. npm start

### Expected behavior

V11 Build Errors with Webpack

package.json

{
....
"webpack": "4.44.2",
}

### Screenshots or Videos

![image_2023_02_14T11_22_08_159Z](https://user-images.githubusercontent.com/87180510/218722967-cc127007-424b-4459-bc3b-0bc72d69bdb7.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment] 2023-02-16 11:25
duplicate of #2453 - you need to transpile React Flow.

**Closed by moklick** 2023-02-16 11:25 UTC
