### ISSUE TITLE
Multiple Restoring after drag is not working

### ISSUE THREAD

**Issue by theashishmaurya** [wbkd/react-flow#1425] opened 2021-08-08 17:50 UTC
Save and Restore is working fine if you save the elements and then drag things around and click on Restore everything is restored but after I change things further and then click on restore elements are not getting restored to their saved state.

for recreating this issue 
1) go to https://reactflow.dev/examples/save-and-restore/
2) Drag things around and save and again drag things around and restore. (It is working fine till then)
3) Drag things further and try restoring them to the saved state. It is not working.

**Comment by tshana** [comment] 2021-08-09 18:21
Yeah, I think I have a similar issue where the nodes are not being restored properly. I don't know if this will be helpful, but I think it might have to do with how the state is only causing React to re-render if an element is deleted or added into the flow since it's just checking the Elements array indexes and not the x/y positions of each node/edge to detect change. 

(Please delete my comment if this is not true.) I am currently trying to resolve this "issue" as well.

**Comment by tshana** [comment] 2021-08-09 19:13
I might have found a workaround. In the onRestore callback I set the elements to an empty array while waiting to get a response from the saved data. Seems like it restores properly now (haven't tested all cases yet).

```
  const onRestore = useCallback(() => {
    const restoreFlow = async () => {
      setElements([])
      const flow = await localforage.getItem(flowKey);
      
      if (flow) {
        setElements(flow.elements || []);
             ...
      }
    };
      restoreFlow();
  }, [setElements, transform]);
```

**Comment by Ashumaurya** [comment] 2021-08-10 14:24
Hello  @tshana 
I too actually think the problem is that the page is not rerendering for some reason and I think you found a good workaround to the problem, but do let me know if you find the root cause. Just in case if you wanna work with me feel free to email me.

**Comment by jossh88** [comment] 2021-08-16 05:09
https://github.com/wbkd/react-flow/issues/916#issuecomment-788095320

**Comment by datoslabs** [comment] 2021-08-16 19:15
This problem is related to #1440.  I created the following scenarios and output the `node.position` as well as `node.__rf.position` for each scenario to help demonstrate how node drag causes the API's internal states (ie `node.position` and `node.__rf.position`) to get out of sync resulting in node position not getting updated in accordance to `node.position` property.

1.  a)Drag Node 2 to far-right, b)save, c)drag Node 2 to far-left, d)restore.  This appears to be working because Node 2's `node.position` is different from internal state's `node.position`:
```
onNodeDragStart: id:2 node.position:{x:100, y:200}, node.__rf.position:{x:100, y:200}
onNodeDragStop: id:2 node.position:{x:100, y:200}, node.__rf.position:{x:709, y:242}

Following node positions are saved:
 	id:1 node.position:{x:100, y:100}
	id:2 node.position:{x:709, y:242}

onNodeDragStart: id:2 node.position:{x:100, y:200}, node.__rf.position:{x:709, y:242}
onNodeDragStop: id:2 node.position:{x:100, y:200}, node.__rf.position:{x:-11, y:246}

Internal state before restore:
 	id:1 node.position:{x:100, y:100}, node.__rf.position:{x:100, y:100}
 	id:2 node.position:{x:100, y:200}, node.__rf.position:{x:-11, y:246}
Following node positions are restored:
 	id:1 node.position:{x:100, y:100}
	id:2 node.position:{x:709, y:242}
Internal state after restore:
 	id:1 node.position:{x:100, y:100}, node.__rf.position:{x:100, y:100}
	id:2 node.position:{x:100, y:200}, node.__rf.position:{x:709, y:242}
```

2.  a)Drag Node 2 to far-right, b)save, c)drag Node 1 to far-right, d)restore.  This does not work because Node 1's `node.position` are the same before and after the restore and since the `SET_ELEMENTS` reducer was checking node.position, it did not detect any changes to Node 1 thus did not restore Node 1's position to its original state of (100,100):
```
onNodeDragStart: id:2 node.position:{x:100, y:200}, node.__rf.position:{x:100, y:200}
onNodeDragStop: id:2 node.position:{x:100, y:200}, node.__rf.position:{x:641, y:246}

Following node positions are saved:
 	id:1 node.position:{x:100, y:100}
	id:2 node.position:{x:641, y:246}

onNodeDragStart: id:1 node.position:{x:100, y:100}, node.__rf.position:{x:100, y:100}
onNodeDragStop: id:1 node.position:{x:100, y:100}, node.__rf.position:{x:785, y:100}

Internal state before restore:
 	id:1 node.position:{x:100, y:100}, node.__rf.position:{x:785, y:100}
 	id:2 node.position:{x:100, y:200}, node.__rf.position:{x:641, y:246}
Following node positions are restored:
 	id:1 node.position:{x:100, y:100}
	id:2 node.position:{x:641, y:246}
Internal state after restore:
 	id:1 node.position:{x:100, y:100}, node.__rf.position:{x:785, y:100}
 	id:2 node.position:{x:100, y:200}, node.__rf.position:{x:641, y:246}
```
3.  a)Drag Node 2 to far-right, b)save, c)drag Node 1 to far-right, d)drag Node 2 to far-left, e) restore.  This does not work for the same reason as scenario 2.
```
onNodeDragStart: id:2 node.position:{x:100, y:200}, node.__rf.position:{x:100, y:200}
onNodeDragStop: id:2 node.position:{x:100, y:200}, node.__rf.position:{x:856, y:232}

Following node positions are saved:
 	id:1 node.position:{x:100, y:100}
	id:2 node.position:{x:856, y:232}

onNodeDragStart: id:1 node.position:{x:100, y:100}, node.__rf.position:{x:100, y:100}
onNodeDragStop: id:1 node.position:{x:100, y:100}, node.__rf.position:{x:819, y:92}

onNodeDragStart: id:2 node.position:{x:100, y:200}, node.__rf.position:{x:856, y:232}
onNodeDragStop: id:2 node.position:{x:100, y:200}, node.__rf.position:{x:-53, y:179}

Internal state before restore:
 	id:1 node.position:{x:100, y:100}, node.__rf.position:{x:819, y:92}
 	id:2 node.position:{x:100, y:200}, node.__rf.position:{x:-53, y:179}
Following node positions are restored:
 	id:1 node.position:{x:100, y:100}
	id:2 node.position:{x:856, y:232}
Internal state after restore:
 	id:1 node.position:{x:100, y:100}, node.__rf.position:{x:819, y:92}
 	id:2 node.position:{x:100, y:200}, node.__rf.position:{x:856, y:232}
```

**Comment by moklick** [comment] 2022-03-15 10:08
I will close this issue because we've rewritten lots of parts in v10 that play a role here. We don't have `__.position` anymore and it can't happen that your nodes are out of sync.

**Closed by moklick** 2022-03-15 10:08 UTC
