### ISSUE TITLE
Screenshots breaks ReactFlow interaction. Zoom in/out, X/Y position changing is also brakes. 

### ISSUE THREAD

**Issue by enshtein06** [wbkd/react-flow#1936] opened 2022-03-01 19:55 UTC
### Describe the Bug

When we try to record screen or make a screenshot the ReactFlow canvas becomes non-intractable. Controls are still clickable, but it doesn't change anything on the canvas. After some time (about 10-20 seconds) becomes intractable.

### Steps to Reproduce the Bug or Issue

1. Press shift+command+4 to capture a picture of the screen
2. canvas becomes non-interactable.

### Expected behavior

As a user, I expect canvas to continue being intractable.

### Screenshots or Videos

Uploading IMG_0138.MOV…

### Platform

- OS: MacOS Monterey
- Browser: Google Chrome
- Version: 98.0.4758.102

### Additional context

I do provide screen record using Iphone, because it's not possible to record how I make screenshots from mac itself. I'm sorry about the quality of the record. 
On the record I made a screenshot using `shift+command+4`. Then I tried to scroll on X and Y axes and zoom-in zoom-out. Then I've tried to click controls. Animation of controls still work, but there is no changes on the canvas.
Please ask me if you need any additional context. 
Regards.

**Comment by moklick** [comment] 2022-03-01 22:49
hey @enshtein06 

I will close this, because it's a duplicate of #824

**Closed by moklick** 2022-03-01 22:49 UTC
