### ISSUE TITLE
antd-dropdown doesn't close on clicking on an empty flow area

### ISSUE THREAD

**Issue by CKanishka** [wbkd/react-flow#1915] opened 2022-02-21 13:22 UTC
### Describe the Bug

I am using an antd-dropdown in a page and the dropdown doesn't close on clicking any blank area on the flow but closes when I set `paneMoveable=false`. I have specified antd library for now but I think the behaviour will be same for any implementation where we have to track click events outside a component, and if the click happens within the flow that seems 

### Your Example Website or App

https://codesandbox.io/s/react-flow-demo-forked-h8btcn?file=/src/App.js

### Steps to Reproduce the Bug or Issue

1) Go to the sample link
2) Click on Dropdown button
3) Once the dropdown is open, clicking a blank area on the flow will not close the dropdown

### Expected behavior

The dropdown should close on clicking anywhere on the flow.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 98

**Comment by CKanishka** [comment] 2022-02-21 13:23
@moklick Any help will be highly appreciated here

**Comment by ItsJimi** [comment] 2022-02-22 14:00
I'm really interested too, I'm using an outside click in a custom component and when I click on blank area, I don't have events.

**Comment by moklick** [comment] 2022-02-22 16:13
duplicate of #1676 . Should be fixed with the v10 release

**Closed by moklick** 2022-02-22 16:13 UTC
