### ISSUE TITLE
After migrating to V11 getting some horrible error

### ISSUE THREAD

**Issue by Faizantanveer550** [wbkd/react-flow#3504] opened 2023-10-15 12:01 UTC
```
### Describe the Bug

`{
  "name": "dvsum-react-poc",
  "version": "0.1.0",
  "private": true,
  "proxy": "https://sr54eeuelk.execute-api.us-west-2.amazonaws.com",
  "dependencies": {
    "@ant-design/icons": "^4.6.2",
    "@hookform/resolvers": "^2.7.0",
    "@k2/d3-viz": "^1.2.1",
    "@k2/rv-viz": "^1.2.1",
    "@k2/ui": "^1.2.1",
    "@popperjs/core": "^2.11.6",
    "@reduxjs/toolkit": "^1.6.1",
    "@sqltools/formatter": "^1.2.5",
    "@tisoap/react-flow-smart-edge": "^2.0.0",
    "@types/ws": "^8.5.3",
    "ag-grid-community": "^25.3.0",
    "ag-grid-enterprise": "^25.3.0",
    "ag-grid-react": "^25.3.0",
    "antd": "^4.16.8",
    "aws-amplify": "^4.2.4",
    "axios": "^0.21.1",
    "csvtojson": "^2.0.10",
    "dagre": "^0.8.5",
    "date-fns": "^2.25.0",
    "html-react-parser": "^1.4.0",
    "ramda": "^0.28.0",
    "rc-picker": "^2.5.19",
    "react": "^17.0.2",
    "react-beautiful-dnd": "^13.1.0",
    "react-confetti": "^6.1.0",
    "react-cookie": "^4.1.1",
    "react-dom": "^17.0.2",
    "react-error-boundary": "^3.1.4",
    "react-hook-form": "^7.11.1",
    "react-icons": "^4.2.0",
    "react-query": "^3.19.0",
    "react-quill": "^2.0.0",
    "react-redux": "^7.2.4",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^5.0.1",
    "react-tiny-link": "^3.6.1",
    "react-use-websocket": "^4.2.0",
    "react-virtuoso": "^3.1.5",
    "reactflow": "^11.9.3",
    "read-excel-file": "^5.2.26",
    "recharts": "^2.5.0",
    "sql-formatter": "^12.1.0",
    "styled-components": "^5.2.1",
    "typescript": "^4.1.2",
    "usehooks-ts": "^2.9.1",
    "web-vitals": "^1.0.1",
    "ws": "^4.1.0",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^6.3.5",
    "@storybook/addon-essentials": "^6.3.5",
    "@storybook/addon-links": "^6.3.5",
    "@storybook/react": "^6.3.7",
    "@testing-library/dom": "7.29.0",
    "@testing-library/jest-dom": "5.11.6",
    "@testing-library/react": "11.2.2",
    "@testing-library/user-event": "12.6.0",
    "@types/axios": "^0.14.0",
    "@types/chrome": "^0.0.179",
    "@types/dagre": "^0.7.47",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-beautiful-dnd": "^13.1.1",
    "@types/react-dom": "^17.0.0",
    "@types/react-router-dom": "^5.1.6",
    "@types/react-vis": "^1.11.11",
    "@types/styled-components": "^5.1.4",
    "@types/uuid": "^8.3.1",
    "@types/yup": "^0.29.10",
    "@typescript-eslint/eslint-plugin": "^2.5.0",
    "@typescript-eslint/parser": "^4.20.0",
    "cross-env": "7.0.3",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-prettier": "^6.4.0",
    "eslint-config-react-app": "^5.0.1",
    "eslint-loader": "2.2.1",
    "eslint-plugin-filenames": "^1.3.2",
    "eslint-plugin-flowtype": "3.13.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-react": "^7.16.0",
    "eslint-plugin-react-hooks": "^1.6.1",
    "husky": "^4.3.0",
    "lint-staged": "^10.5.3",
    "msw": "^0.33.0",
    "storybook-addon-deps": "^2.2.0",
    "use-clipboard-copy": "^0.2.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook",
    "lint": "eslint --ext js,jsx,ts,tsx src",
    "lint:fix": "eslint --ext js,jsx,ts,tsx src --cache --fix"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "pre-push": "lint-staged"
    }
  },
  "lint-staged": {
    "src/**/*.{js,jsx,ts,tsx}": [
      "eslint './src/**' --cache --report-unused-disable-directives"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "msw": {
    "workerDirectory": "public"
  }
}
`

I just upgraded my react scripts because without it it was giving me some babel-loader issue

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

- Upgrade react flow version to latest
- Then upgrade react script version

### Expected behavior

It shouldn't give this kind of error

### Screenshots or Videos

![image](https://github.com/wbkd/react-flow/assets/41286767/b0c7c7fa-dc80-4d69-a9f4-d981fe4ce56d)


### Platform

- OS:  windows
- Browser: [ Chrome, Safari, Firefox]
- Version: [e.g. 91.1]


### Additional context

_No response_
```

**Comment by moklick** [comment] 2023-10-16 08:10
duplicate of #3505

**Closed by moklick** 2023-10-16 08:10 UTC
