### ISSUE TITLE
Edges can become misaligned with handles

### ISSUE THREAD

**Issue by TippyLion28** [wbkd/react-flow#1136] opened 2021-04-26 11:01 UTC
![misaligned edges](https://user-images.githubusercontent.com/25936204/116072362-e0aa0780-a686-11eb-837e-633242a37de1.png)
As seen above. It seems to happen more frequently when switching tabs or between Windows, as well as when dragging around the canvas a lot. 

Not sure if this is the case, but I think it's also more likely to happen when saving the react file and react performs an in-place reload via the websocket.

**Comment by moklick** [comment] 2021-04-27 10:31
I will close this in favour of #1075 . Unfortunately I am still not able to reproduce this. Which browser are you using?

**Closed by moklick** 2021-04-27 10:31 UTC
