### ISSUE TITLE
Loader issue on create-react-app with craco

### ISSUE THREAD

**Issue by Siddharth009** [wbkd/react-flow#3104] opened 2023-05-31 04:08 UTC
### Describe the Bug

Got loader issue while running the starting code

### Steps to Reproduce the Bug or Issue

Try to use <ReactFlow /> component from docs

### Expected behavior

Expected to run smoothly but got an error

### Screenshots or Videos

![image](https://github.com/wbkd/react-flow/assets/25169558/1f9785b2-e1ad-4a14-a956-b1745de1995e)

my craco config:

```
const CracoLessPlugin = require('craco-less');

const esModules = [
  // for dnd
  'react-dnd',
  'core-dnd',
  '@react-dnd',
  'dnd-core',
  'react-dnd-html5-backend',
  // for markdown
  'react-markdown',
  'vfile',
  'unist-.+',
  'unified',
  'bail',
  'is-plain-obj',
  'trough',
  'remark-.+',
  'mdast-util-.+',
  'micromark',
  'parse-entities',
  'character-entities',
  'property-information',
  'comma-separated-tokens',
  'hast-util-whitespace',
  'remark-.+',
  'space-separated-tokens',
  'decode-named-character-reference',
  'ccount',
  'escape-string-regexp',
  'markdown-table',
  'trim-lines',
  //
].join('|');

module.exports = {
  eslint: {
    enable: false,
  },
  plugins: [
    {
      plugin: CracoLessPlugin,
      options: {
        lessLoaderOptions: {
          lessOptions: {
            modifyVars: {
              'primary-color': '#4e677f',
              //bg color
              '@background-color-light': '#b7c3c8',
              //paddings
              '@padding-lg': '16px',
              '@padding-md': '12px',
              '@padding-sm': '10px',
              //margins
              '@margin-lg': '16px',
              '@margin-md': '12px',
              '@margin-sm': '10px',
              //heights
              '@height-base': '24px',
              '@height-lg': '36px',
              '@height-sm': '18px',
              //fonts
              '@font-size-base': '13px',
              '@font-size-sm': '11px',
              //table
              '@table-row-hover-bg:': 'rgb(205, 232, 255)',
              '@table-padding-vertical': '3px',
              '@table-padding-horizontal': '6px',
              '@table-header-bg': 'lighten(@background-color-light, 35%)',
              //modal
              '@modal-header-bg': '#fff',
              '@menu-dark-color': '#fff',
              // '@menu-dark-bg': 'rgb(58, 61, 70)',
              '@modal-close-color': '#000',
              '@modal-header-title-font-size': '@font-size-base',
              '@modal-content-bg': '#fff',
              '@modal-heading-color': '#000',

              '@modal-header-padding': '10px 16px',
              // collapsible
              '@collapse-header-bg': '@background-color-light',
              //popover
              '@popover-min-width': '200px',
              '@popover-max-height': '32px',

              //card
              '@card-head-background': '#b7c3c8',
              '@card-head-padding': '6px',
              '@card-head-height': '@height-sm',
              '@card-padding-base': '8px',
              '@card-padding-sm': '@padding-sm',
              '@card-inner-head-padding': '9px',
              //Tabs

              '@tabs-card-active-color': '#fff',
              '@tabs-card-head-background': '#fff',

              '@tabs-bar-margin': '0px',
              '@primary-1': '#b7c3c83d',
              '@item-hover-bg': '@primary-1',
              '@table-row-hover-bg': '@primary-1',
              'layout-body-background': '#f0f0f5',
              'layout-header-background': 'rgb(58, 61, 70)',
              '@layout-header-padding': 0,
              '@layout-footer-padding': '0 0 0 10px',
              '@layout-header-height': '40px',

              //Page Header
              '@page-header-padding': '@padding-md',
              '@page-header-padding-vertical': '@padding-md',
              '@page-header-padding-breadcrumb': '@padding-sm',
              '@page-header-content-padding-vertical': '@padding-sm',
              '@page-header-back-color': '#000',
              '@page-header-ghost-bg': 'inherit',
              '@page-header-heading-title': '16px',
              '@page-header-heading-sub-title': '14px',
              '@page-header-tabs-tab-font-size': '16px',

              //shadow

              '@shadow-2':
                '0 3px 6px -4px rgb(0 0 0 / 30%), 0 6px 16px 0 rgb(0 0 0 / 15%), 0 9px 28px 8px rgb(0 0 0 / 11%)',
            },
            javascriptEnabled: true,
          },
        },
      },
    },
  ],
  jest: {
    testEnvironment: 'node',
    configure: (jestConfig, { env, paths, resolve, rootDir }) => {
      jestConfig.transformIgnorePatterns = [`/node_modules/(?!(${esModules}))`];
      jestConfig.setupFilesAfterEnv = ['<rootDir>/src/setupTests.tsx'];

      return jestConfig;
    },
  },
};
```

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment] 2023-06-08 14:11
You need to transpile React Flow. Could you try to add it to the `esModules` array?

**Comment by moklick** [comment] 2023-06-08 14:11
duplicate of #2453

**Closed by moklick** 2023-06-08 14:11 UTC
