### ISSUE TITLE
React flow stops responding after pressing shift+command+4 on macOS chrome

### ISSUE THREAD

**Issue by 255153YW** [wbkd/react-flow#1711] opened 2021-11-24 12:31 UTC
Hello,

As described in the title, you can easily reproduce this by opening https://reactflow.dev/examples/ on chrome in macOS and press shift+command+4.

After taking a screenshot, react flow stops responding.
The bug is not present on Firefox browser in macOS.

**Comment by xplato** [comment] 2021-11-24 16:51
Duplicate of #824

**Closed** 2021-12-06 07:22 UTC
