### ISSUE TITLE
Persist selection box all the time whenever multiple nodes are selected whether by selection box or click select

### ISSUE THREAD

**Issue by ratnajeetshyamkunwar** [wbkd/react-flow#2889] opened 2023-03-06 06:31 UTC
### Describe the Bug

Not sure if it falls under feature request so starting as bug.

Is there any way to persist the selection box whenever any of the nodes are selected?

Requirement: When the network is large and selected nodes are out of viewport, it is hard for user to keep track of all the selected nodes. A persisting boundary will help keep track of all the selected nodes.

### Steps to Reproduce the Bug or Issue

1. open any network
2. start multiselection by box selection
3. when clicking outside selection box, or cmd+click selecting other nodes, the selection box disappearsthe 

### Expected behavior

The selection box should not disappear

### Screenshots or Videos

https://user-images.githubusercontent.com/36529897/223035120-ff7b5d4a-5e45-4c3f-af68-23f16812a2c5.mov

### Platform

- OS: macOS
- Browser: Chrome
- Version: 110.0.5481.177 (Official Build) (x86_64)
- react-flow version: 11.5.6

**Comment by moklick** [comment] 2023-03-06 15:57
duplicate of #2782

**Closed by moklick** 2023-03-06 15:57 UTC

**Comment by xuanaxuan** [comment] 2023-06-15 12:52
I saw that this issue has been closed. Has it been resolved in the new version?

**Comment by moklick** [comment] 2023-06-15 15:25
It has been closed because it's a duplicate issue (which is still open)
