### ISSUE TITLE
Event is not triggered when holding the on key and press the other key for key combination in UseKeyPress hook

### ISSUE THREAD

**Issue by Max-ChenFei** [wbkd/react-flow#2957] opened 2023-03-24 16:18 UTC
### Describe the Bug

>https://reactflow.dev/docs/api/hooks/use-key-press/ 
a string like "Meta+s" (event.code or event.key combined with a + sign) for a key combination

When we press the key combination, no issue at all. 
However, the press event won't be triggered when the user holds the modifier key (for example `Control`) and presses the key.  

One use case could be holding the `control` key and pressing `v` multiple times to paste multiple times.

### Your Example Website or App

https://codesandbox.io/s/cranky-mirzakhani-u158pn?file=/App.js

### Steps to Reproduce the Bug or Issue

In the sandbox, if I press the `Control+v`, the console will print the log, but if I hold the control and press the `v`, the console will not log any message.

### Expected behavior

When I hold the `control` and press `v`, the `useEffect` will be triggered.

### Platform

- OS: Windows
- Browser: Edge

**Comment by moklick** [comment] 2023-03-27 20:38
duplicate of #2248

**Closed by moklick** 2023-03-27 20:38 UTC
