### ISSUE TITLE
edges not rendered to JSDOM when testing with Jest and React Testing Library

### ISSUE THREAD

**Issue by kislakiruben** [wbkd/react-flow#716] opened 2020-11-23 11:44 UTC
Hi!

I'm having some issue on making the nodes and edges to show up when I'm rendering the graph to JSDOM with Jest and React Testing Library. I have the following set up:

```js
//App.js
import ReactFlow from "react-flow-renderer";

const App = () => (
  <ReactFlow
    elements={[
      {
        data: { label: "a" },
        id: "b",
        position: { x: 10, y: 10 },
      },
      {
        data: { label: "b" },
        id: "a",
        position: { x: 10, y: 80 },
      },
      {
        id: "edge-a-b",
        source: "a",
        target: "b",
      },
    ]}
  />
);
```
And then I try to test it:
```js
//App.test.js
import { render } from "@testing-library/react";

import App from "./App";

it("should render", async () => {
  const { debug, getByText } = render(<App />);

  debug(); 
  expect(getByText("a")).toBeInTheDocument();
});
```

The test fails because the node is not rendered. If I do a `debug`, I can see that the wrapper elements for the graph are being rendered, but no nodes or edges.

```html
<body>
  <div>
    <div
      class="react-flow"
    >
      <div
        class="react-flow__renderer react-flow__zoompane"
      >
        <div
          class="react-flow__nodes"
          style="transform: translate(0px,0px) scale(1);"
        />
        <svg
          class="react-flow__edges"
          height="500"
          width="500"
        >
          <defs>
            <marker
              class="react-flow__arrowhead"
              id="react-flow__arrowclosed"
              markerHeight="12.5"
              markerWidth="12.5"
              orient="auto"
              refX="0"
              refY="0"
              viewBox="-10 -10 20 20"
            >
              <polyline
                fill="#b1b1b7"
                points="-5,-4 0,0 -5,4 -5,-4"
                stroke="#b1b1b7"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="1"
              />
            </marker>
            <marker
              class="react-flow__arrowhead"
              id="react-flow__arrow"
              markerHeight="12.5"
              markerWidth="12.5"
              orient="auto"
              refX="0"
              refY="0"
              viewBox="-10 -10 20 20"
            >
              <polyline
                fill="none"
                points="-5,-4 0,0 -5,4"
                stroke="#b1b1b7"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="1.5"
              />
            </marker>
          </defs>
          <g
            transform="translate(0,0) scale(1)"
          />
        </svg>
        <div
          class="react-flow__pane"
        />
      </div>
    </div>
  </div>
</body>
```

I wanted to set up a codesandbox, but I couldn't get to polyfill `ResizeObserver`.

Any ideas on what might be going on and how to 'fix' it?

EDIT: if I pass a callback to `onLoad`, I can see the elements in there:

```js
import ReactFlow from "react-flow-renderer";

const App = () => {
  const onLoad = (instance) => {
    console.log(instance.getElements());
  };

  return (<ReactFlow elements={[...]} onLoad={onLoad} />);
};

**Comment by moklick** [comment] 2020-11-26 16:14
Hey @kislakiruben 

I could imagine that react flow is not finished with rendering. It seems that it only rendered the first tick. Maybe you could use `waitFor` from `@testing-library/react`?

**Comment by kislakiruben** [comment] 2020-11-26 20:56
yes, I tried to do that, but I got the same result. I'm wondering whether it has anything to do with how easy-peasy is initializing the state.

**Comment by MatiasCiccone** [comment] 2020-12-09 17:53
I have the same issue. I'll try to create a sandbox for this

**Comment by MatiasCiccone** [comment] 2020-12-09 19:13
This works for me locally but I'm not able to make it work in the sandbox. I may be missing something. Here is the link if anyone wants to give it a try https://codesandbox.io/s/blissful-spence-hnozn

**Comment by moklick** [comment] 2021-01-20 14:20
Could you solve this @kislakiruben ?

**Comment by kislakiruben** [comment] 2021-01-20 17:15
> Could you solve this @kislakiruben ?

Not really. I ditched writing unit tests for the graph implementaion.

**Comment by moklick** [comment] 2021-01-20 17:34
All I needed to do is to mock the ResizeObserver to get this running. I used a fresh CRA and the latest version (8.4.1) of react flow.

**Comment by MatiasCiccone** [comment] 2021-01-21 17:24
@moklick can you show how you mocked the ResizeObserver?

**Comment by moklick** [comment] 2021-01-21 18:27
in `setupTests.js`:

```js
import { ResizeObserver } from '@juggle/resize-observer';

global.ResizeObserver = ResizeObserver;
```

**Comment by moklick** [comment] 2021-01-23 09:20
Could you check if it works for you with the current version @kislakiruben ?

**Comment by kislakiruben** [comment] 2021-01-23 10:23
@moklick it looks like it works with the latest version (`8.5.0`). we're using `8.0.0-next.4`. thank you for fixing this!

**Comment by kislakiruben** [comment] 2021-01-23 10:29
I'm not sure, but I believe this commit fixed it: https://github.com/wbkd/react-flow/commit/d6a410a0a3ef7ae462065b196d5aa83583f3d156

**Comment by moklick** [comment] 2021-01-23 12:49
Ok, cool! Feel free to re-open this issue if you encounter a problem with react-flow + testing-library/react.

**Comment by MatiasCiccone** [comment] 2021-01-27 18:30
I just checked this with 8.7.0 and it is working.

**Comment by gfox1984** [comment] 2021-03-24 13:00
Hey, sorry I'm a bit confused here. What exactly is working? I'm running version 9.3.2 (the latest), and I still have the original problem that no edges or nodes are rendered in the tests.

I tried adding:

```
import { ResizeObserver } from '@juggle/resize-observer';
global.ResizeObserver = ResizeObserver;
```

which fixes this error:

`  console.error
    Error: Uncaught [ReferenceError: ResizeObserver is not defined]`

But still no nodes and edges are rendered.

Notes:

1. I still have the following warning `console.warn     The React Flow parent container needs a width and a height to render the graph.`, despite wrapping ReactFlow into `<div style={{ width: 500, height: 500 }}>`
2. I tried setting the following option `onlyRenderVisibleElements={false}`, but it did not make a difference

@MatiasCiccone @kislakiruben can you confirm you are able to access the elements within react flow in your tests?

**Comment by m04r** [comment] 2021-05-12 00:49
i am having a similar issue.

when running tests, nodes are being rendered, but edges are not. i am using version `9.0.1` and `ResizeObserver` is being mocked as described above.

**Comment by zheller** [comment] 2021-08-22 17:47
Hey there,

Ran into this bug. I'm pretty sure I found the root problem in react-testing library. First, like folks have noted you need to make sure to mock the RenderObserver for things to really just work to begin with. After that, nodes will render but edges don't. Edges aren't being rendered because in edge initialization it bails out if the source node `__rf.width` isn't set (https://github.com/wbkd/react-flow/blob/main/src/container/EdgeRenderer/index.tsx#L90). This width is set by getting `node.offsetWidth` here: https://github.com/wbkd/react-flow/blob/41db69e06c22d278657ba810198f371119b4972b/src/utils/index.ts#L14.

React-testing-library uses jsdom under the hood, which by design doesn't implement layout, but this is effectively the same problem people are discussing here: https://github.com/jsdom/jsdom/issues/135, and can pretty much be solved by putting this in your code:
```javascript
Object.defineProperties(window.HTMLElement.prototype, {
  offsetHeight: {
    get() { return parseFloat(this.style.height) || 1; },
  },
  offsetWidth: {
    get() { return parseFloat(this.style.width) || 1; },
  },
});
```
To stub out the methods to ensure node width isn't falsy, and then you get edges rendered.

I'm not really sure if there is much that needs to be fixed in this library, since I don't think it makes sense for it to be aware of the fact that it't not actually being rendered... but I think it might be solved by an example.

**Comment by Michael-Xie** [comment] 2021-09-08 23:39
> ```js
> Object.defineProperties(window.HTMLElement.prototype, {
>   offsetHeight: {
>     get() { return parseFloat(this.style.height) || 1; },
>   },
>   offsetWidth: {
>     get() { return parseFloat(this.style.width) || 1; },
>   },
> });
> ```

where would you put this code in?

When I put it into `setupTests.js` or the test file, it would give this warning:
`console.error
    Warning: validateDOMNesting(...): <body> cannot appear as a child of <foreignObject>.`

**Comment by gfox1984** [comment] 2021-09-09 07:21
I put it in the test file itself (eg: MyComponent.test.tsx) inside `beforeAll`. That's my setup:

```
beforeAll(() => {
  // Setup ResizeObserver and offset* properties
  // see: https://github.com/wbkd/react-flow/issues/716

  window.ResizeObserver =
    window.ResizeObserver ||
    jest.fn().mockImplementation(() => ({
      disconnect: jest.fn(),
      observe: jest.fn(),
      unobserve: jest.fn(),
    }));

  Object.defineProperties(window.HTMLElement.prototype, {
    offsetHeight: {
      get() {
        return parseFloat(this.style.height) || 1;
      },
    },
    offsetWidth: {
      get() {
        return parseFloat(this.style.width) || 1;
      },
    },
  });

  (window.SVGElement as any).prototype.getBBox = () => ({x:0, y:0, width: 0, height: 0});
});
```

@moklick I think it would be useful to add an example to the site. Most people use Jest + Testing Library in their application, and setting up tests is a bit challenging.

**Comment by Michael-Xie** [comment] 2021-09-09 12:47
> > ```js
> > Object.defineProperties(window.HTMLElement.prototype, {
> >   offsetHeight: {
> >     get() { return parseFloat(this.style.height) || 1; },
> >   },
> >   offsetWidth: {
> >     get() { return parseFloat(this.style.width) || 1; },
> >   },
> > });
> > ```
> 
> where would you put this code in?
> 
> When I put it into `setupTests.js` or the test file, it would give this warning:
> `console.error Warning: validateDOMNesting(...): <body> cannot appear as a child of <foreignObject>.`

@gfox1984 Thanks for providing the test file. It added coverage onto the CustomEdge component when I render the React Flow diagram. 

As for my specific warning/error that I am seeing, I changed the `<body>` tag used `<foreignObject>` to `div` instead to resolve it. The `<body>` tag was used in the [Edge with Button example](https://reactflow.dev/examples/edge-with-button), and am wondering if that needs to be updated to avoid this warning.

**Comment by bipinbabu-collectAI** [comment] 2022-04-27 19:52
I could still see this issue in the latest version, edges are not rendering. Do you have any solution?

**Comment by bipin-u-babu** [comment] 2022-04-27 20:24
@gfox1984, @[Zachary Heller](https://github.com/zheller): I could still see this issue in the latest version, edges are not rendering in test. Do you have any solution?

**Comment by Bars92** [comment] 2022-08-29 13:54
Sadly I am also experiencing the same issue where edges are not visible after applying https://github.com/wbkd/react-flow/issues/716#issuecomment-915831149. It does seem that the edges are been calculated but never rendered:

```html
<svg
  class="react-flow__edges react-flow__container"
  height="1"
  style="z-index: 0;"
  width="1"
>
  <defs />
  <g /> <----
</svg>
```

using `react v18.2`, `react-flow-renderer: v10.3.14` and `@testing-library/react v13.3`. Wasn't able to get the edges rendered, if anyone has an idea, I'll have to dig around more and debug.

**Comment by moklick** [comment] 2022-09-05 11:13
Hey everyone,

I looked into this but I haven't found a good solution yet. There are two problems:

1. ReactFlow measures nodes and updates the dimensions via ResizeObserver. The ResizeObserver doesn't seem to work while running tests. This is fixable. I could update the nodes immediately while we are in a testing environment. 
2. When I apply the fix mentioned above, I get another error: `"[TypeError: window.DOMMatrixReadOnly is not a constructor"` I don't understand why this is not supported by jest or why I can't find anything about it. It's a dom library that is supoorted by all browsers https://developer.mozilla.org/en-US/docs/Web/API/DOMMatrixReadOnly 

Can anyone help here?

**Comment by bcakmakoglu** [comment] 2022-09-05 11:18
@moklick Maybe it needs to be mocked in the jest environment? Seems like documentation on this particular API is ... non-existent :(

I just found this [gist](https://gist.github.com/YonatanKra/b037c8504f2db6443ce2ea252e916894) that seems somewhat relevant.

**Comment by moklick** [comment] 2022-09-05 11:32
Ok. I have an idea.. I will just do something like this:

```js 
export function getScaleFromElement(element: HTMLDivElement): number {
  if (window.DOMMatrixReadOnly) {
    const style = window.getComputedStyle(element);
    const { m22 } = new window.DOMMatrixReadOnly(style.transform);
    return m22;
  }

  const scale = element.style?.transform?.match(/scale\(([1-9.])\)/)?.[1];
  return scale !== undefined ? +scale : 1;
}
```

**Comment by gfox1984** [comment] 2022-09-05 12:17
Hey, sorry, I'm late to the party. I haven't updated reactflow in a while, so yes it's possible that there's more that needs to be mocked now. I guess that window.DOMMatrixReadOnly needs a polyfill.

I haven't tried it, but I see that there is one available here: https://github.com/thednp/dommatrix. Then you should be able to do something like this:

```
import DOMMatrix from 'dommatrix';
...

beforeAll(() => {
  ...  
  window.DOMMatrixReadOnly = DOMMatrix;
});
```

@moklick I'm not sure it's a good idea to start adding fallbacks to the code just for Jest, although I agree that it would be convenient and that it's not really specific to Jest either (you could see it as a general fallback for exotic browsers). But maybe a better approach would be to create an interface for all the DOM-specific operations that are not available in the testing environment, then add an optional prop to the ReactFlow Provider to be able pass an implementation for it (= dependency injection). If not provided, you'd use your default implementation based on the actual DOMMatrixReadOnly, ResizeObserver, etc. In Jest, we'd just use our own (or you could also provide a package (or export some utilities) to help with that.)

**Comment by moklick** [comment] 2022-09-05 12:20
@gfox1984 I agree! Would be better to mock things from within `setupTests`. Now that I am working on it, do you know how to mock `offsetWidth` and `offsetHeight` of an element (that's another issue I just encountered)? I can't find anything about it.

**Comment by gfox1984** [comment] 2022-09-05 12:28
> @gfox1984 I agree! Would be better to mock things from within `setupTests`. Now that I am working on it, do you know how to mock `offsetWidth` and `offsetHeight` of an element (that's another issue I just encountered)? I can't find anything about it.

You should be able to do this:
```
  Object.defineProperties(window.HTMLElement.prototype, {
    offsetHeight: {
      get() {
        return parseFloat(this.style.height) || 1;
      },
    },
    offsetWidth: {
      get() {
        return parseFloat(this.style.width) || 1;
      },
    },
  });
```

**Comment by moklick** [comment] 2022-09-05 12:35
Thanks @gfox1984.

This is my `setupTests.ts`:


```ts
import { ResizeObserver } from '@juggle/resize-observer';

global.ResizeObserver = ResizeObserver;

// we only use the scale of the matrix (`m22`), that's why we can use this simple mock
class DOMMatrixReadOnly {
  m22: number;
  constructor(transform: string) {
    const scale = transform?.match(/scale\(([1-9.])\)/)?.[1];
    this.m22 = scale !== undefined ? +scale : 1;
  }
}
// @ts-ignore
global.DOMMatrixReadOnly = DOMMatrixReadOnly;

Object.defineProperties(global.HTMLElement.prototype, {
  offsetHeight: {
    get() {
      return parseFloat(this.style.height) || 1;
    },
  },
  offsetWidth: {
    get() {
      return parseFloat(this.style.width) || 1;
    },
  },
});

```

**Comment by moklick** [comment] 2022-09-14 11:04
Good news. I've found a better solution. You can get rid of the `@juggle/resize-observer` dependency and don't need to pass a fake width and height to your nodes in order to test them. The trick is to create a ResizeObserver class that works slighty different than the original one.

Updated `setupTests.ts`:

```ts
// To make sure that the tests are working, it's important that you are using
// this implementation of ResizeObserver and DOMMatrixReadOnly 
class ResizeObserver {
  callback: globalThis.ResizeObserverCallback;

  constructor(callback: globalThis.ResizeObserverCallback) {
    this.callback = callback;
  }

  observe(target: Element) {
    this.callback([{ target } as globalThis.ResizeObserverEntry], this);
  }

  unobserve() {}

  disconnect() {}
}

global.ResizeObserver = ResizeObserver;

class DOMMatrixReadOnly {
  m22: number;
  constructor(transform: string) {
    const scale = transform?.match(/scale\(([1-9.])\)/)?.[1];
    this.m22 = scale !== undefined ? +scale : 1;
  }
}
// @ts-ignore
global.DOMMatrixReadOnly = DOMMatrixReadOnly;

Object.defineProperties(global.HTMLElement.prototype, {
  offsetHeight: {
    get() {
      return parseFloat(this.style.height) || 1;
    },
  },
  offsetWidth: {
    get() {
      return parseFloat(this.style.width) || 1;
    },
  },
});

(global.SVGElement as any).prototype.getBBox = () => ({
  x: 0,
  y: 0,
  width: 0,
  height: 0,
});

export {};
```

I'll updated the docs, too.

**Closed by moklick** 2022-09-14 11:04 UTC
Labels: help wanted

**Comment by Bars92** [comment] 2022-09-29 16:11
Nice ! Thank you @moklick, I applied the changes above and both nodes and edges are now fully visible in my jest tests 👍

**Comment by seunggs** [comment] 2022-10-23 03:10
@Bars92 Are you able to use `user-events` to simulate a `click` event on the node? I can't seem to get it to work.

**Comment by avishwakarmaplex** [comment] 2023-01-31 13:18
@moklick 

Do i need to import it manually inside story-snapshot.test.js?

global.DOMMatrixReadOnly = DOMMatrixReadOnly;

![image](https://user-images.githubusercontent.com/72560398/215771056-a753964b-31bc-4b75-938c-6eca48b3bced.png)

**Comment by avishwakarmaplex** [comment] 2023-02-01 15:57
@moklick did you got chance to look at the issue ?

**Comment by kfirpeled** [comment] 2024-10-15 18:25
> I'll updated the docs, too: https://reactflow.dev/docs/guides/testing/

@moklick attached docs are not working on version 12 (@xyflow/react), the edges are not being rendered.
I tested it using the example app attached in this thread: https://github.com/xyflow/xyflow/issues/2949#issuecomment-2414712828

**Comment by moklick** [comment] 2026-05-06 05:46
solution explained here https://github.com/xyflow/xyflow/issues/2949#issuecomment-4382728527
