### ISSUE TITLE
Did everything still unable to use fitView along side of any external component

### ISSUE THREAD

**Issue by piyusht1402** [wbkd/react-flow#3078] opened 2023-05-21 12:20 UTC
### Describe the Bug

I have been trying to use "fitView" with a custom made button, made for toggling the view of my reactflow diagram from horizontal to vertical, i have tried every method but have failed to make fitView work inside the toggle view function. It either says fitView is not a function(when i use useReactflow for using fitView inside other components). Please help me for fixing this issue.

this is my togglelayout function inside LayoutFlow component, which uses dagre for auto-layouting and also toggles the horizontal and vertical view:

const toggleLayoutDirection = () => {
    setShowEdges(false);
    setZoomOut(true); // Trigger the zoom out animation
    setTimeout(() => {
      const newDirection = layoutDirection === 'BT' ? 'RL' : 'BT';
      setLayoutDirection(newDirection);
      const { nodes: newNodes, edges: newEdges } = getLayoutedElements(
        nodes,
        edges,
        newDirection
      );
      setNodes([...newNodes]);
      setEdges([...newEdges]);
      setZoomClass('');
      setZoomOut(false); // Reset the zoomOut state after the animation is complete
      setShowEdges(true);
    }, 200);
  };

### Steps to Reproduce the Bug or Issue

Just try to use fitview inside any external component

### Expected behavior

It will most of the times say that "fitView is not a function" and if there is no error, the fitview function will not work.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

-Windows 10
-Browser : Chrome
- Verson: 11(reactflow)

**Comment by moklick** [comment] 2023-05-21 14:16
why are you opening an issue and a discussion with the same question? This is really annoying. I will close the issue since it's a duplicate of #3079

**Closed by moklick** 2023-05-21 14:16 UTC

**Comment by piyusht1402** [comment] 2023-05-21 14:40
> why are you opening an issue and a discussion with the same question? This is really annoying. I will close the issue since it's a duplicate of #3079

Since i am a new user here so i didn't know where would be the right place to post this issue, sorry to annoy you.
