### ISSUE TITLE
onNodeClick always triggers position change

### ISSUE THREAD

**Issue by nraskoti92** [wbkd/react-flow#2607] opened 2022-11-28 06:27 UTC
### Describe the Bug

onNodeClick always triggers position change even if not dragged.

### Your Example Website or App

https://codesandbox.io/s/reactflow-onnodeclick-r23qrl?file=/App.js

### Steps to Reproduce the Bug or Issue

1. Go to this [codesandbox](https://codesandbox.io/s/reactflow-onnodeclick-r23qrl?file=/App.js)
2. Observe the count as 0 in the bottom left of the preview
3. Click on the node

### Expected behavior

Position change should not be triggered on node click.

### Platform

- OS: macOS
- Browser: Brave
- Version: 1.45.131

**Comment by chrtze** [comment] 2022-11-28 13:44
Hey, thanks for your issue. The reason for this is that we don't know if you are dragging the node as soon as you are clicking it. Are you facing any issues due to this behavior?

**Comment by nraskoti92** [comment] 2022-11-28 14:17
Hi @chrtze ,
The use case for us is to open a panel on node click. We are also setting the isDirty flag if any node or edge change is happening.
Now even though there are no changes, just opening the panel with a click sets the dirty flag to true which affects the other functionalities. 
Tried with node select change also, but even if we drag the node first select is triggered if already not selected then position.

**Comment by chrtze** [comment] 2022-11-29 12:14
Hey @nraskoti92,

I have tried to reproduce this. When I click a node, the onNodesChange callback gets called with one change which is there to set the `dragging` property. I understand that it is a bit confusing that it has `type: 'position'`. If you want to exclude this change from your logic, you can check if it's a position change but doesn't have a `position` or `positionAbsolute` property.

If you want to open a panel or popup on click, I would recommend to use the `onNodeClick` function for that. If you are listening to the selected node, you could try setting the prop `selectNodesOnDrag` to `false`, too.

Hope this helps!

**Comment by danielgek** [comment] 2022-12-01 15:26
I guess #2622 is kinda related to this because is related with position changes

**Comment by nraskoti92** [comment] 2022-12-06 09:21
Hi @chrtze , I am using uncontrolled flow and not using `onNodesChange` anymore.  I am using `onNodeClick` which is also recommended by you. Since a similar issue has been reported and I guess will be worked upon soon, if you want we can close this issue in favor of the new one.

**Comment by moklick** [comment] 2022-12-08 16:06
closed in favour of #2622

**Closed by moklick** 2022-12-08 16:06 UTC
